# Generated by Django 5.2 on 2025-04-12 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('data', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='WordCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True, verbose_name='Слово')),
                ('translation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Перевод')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.imagemodel', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'Карточка слова',
                'verbose_name_plural': 'Карточки слов',
            },
        ),
    ]
